//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace anketaApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sustem_user
    {
        public int id { get; set; }
        public string surname { get; set; }
        public string name { get; set; }
        public string patronumic { get; set; }
        public string email { get; set; }
        public string password { get; set; }
    }
}
